// AI Frontier - News Data (auto-generated)
// Last update: 2026-06-17（真实来源：阿里、硅基流动、MiniMax、BCG、微软）
var AI_NEWS_DATA = [
  // ===== 2026-06-17 最新资讯（置顶）=====
  {
    "id": "llm-028",
    "title": "阿里发布具身大模型 Qwen-Robot 系列：为机器人装上手脚和大脑",
    "category": "大模型",
    "tag": "发布",
    "tagColor": "blue",
    "icon": "🤖",
    "summary": "6月16日，阿里巴巴发布千问具身智能大模型 Qwen-Robot 系列，包含 VLA 操作模型 Qwen-Robot-Manip、VLN 移动模型 Qwen-Robot-Nav 和世界模型 Qwen-Robot-World 三大模型，为机器人提供完整的具身智能解决方案。",
    "date": "2026-06-17",
    "views": 6842,
    "comments": 234,
    "url": "https://www.aliyun.com"
  },
  {
    "id": "llm-029",
    "title": "硅基流动完成超20亿元B轮融资，日均Token调用量达数万亿",
    "category": "大模型",
    "tag": "融资",
    "tagColor": "green",
    "icon": "💰",
    "summary": "6月16日，硅基流动宣布完成超20亿元B轮融资，由携程战投、晶科能源、金蝶股份等联合投资。过去一年，公司通过'Token工厂'模式提供高效MaaS服务，日均Token调用量达数万亿，营收同比增长超10倍。",
    "date": "2026-06-17",
    "views": 5234,
    "comments": 167,
    "url": "https://siliconflow.cn"
  },
  {
    "id": "llm-030",
    "title": "MiniMax M3 全面接入支付宝 Token Pay，成为全球首批",
    "category": "大模型",
    "tag": "集成",
    "tagColor": "blue",
    "icon": "🇨🇳",
    "summary": "6月16日，MiniMax最新大模型M3全面接入支付宝Token Pay一站式全栈解决方案。MiniMax成为全球首批将Token Pay支付能力融入核心订阅体系的大模型厂商，标志着国内首个面向MaaS支付解决方案投入规模化应用。",
    "date": "2026-06-17",
    "views": 4532,
    "comments": 145,
    "url": "https://www.minimaxi.com"
  },
  {
    "id": "agent-024",
    "title": "BCG万人调研：多数人认为3年内Agent能完成至少一半工作",
    "category": "Agent",
    "tag": "报告",
    "tagColor": "purple",
    "icon": "📊",
    "summary": "波士顿咨询(BCG)最新《AI at Work》报告显示：74%的一线员工已成为AI常规用户，42%的人表示每周节省8小时。多数受访者认为3年内Agent能完成至少一半工作，战略比工具更重要成为核心结论。",
    "date": "2026-06-17",
    "views": 7234,
    "comments": 312,
    "url": "https://www.bcg.com"
  },
  {
    "id": "agent-025",
    "title": "微软考虑采用DeepSeek V4等开源模型，降低Copilot使用成本",
    "category": "Agent",
    "tag": "成本",
    "tagColor": "orange",
    "icon": "💡",
    "summary": "6月17日最新消息：微软正在将Copilot Cowork转向'按使用量计费'模式，并考虑采用DeepSeek V4等开源模型，以解决'AI太贵'的问题。此举标志着大厂开始重视AI应用的成本控制。",
    "date": "2026-06-17",
    "views": 8934,
    "comments": 456,
    "url": "https://www.microsoft.com"
  },
  {
    "id": "paper-029",
    "title": "2026年AI Agent框架六强争霸：LangGraph、Claude Agent SDK领先",
    "category": "学术论文",
    "journal": "技术报告 · 2026-06-17",
    "authors": "多位研究者 · 综合评测",
    "summary": "2026年6月，AI Agent框架从'百花齐放'演变为'六强争霸'：LangGraph、Claude Agent SDK、CrewAI、AutoGPT、OpenClaw、MetaGPT各有侧重，开发者面临选型挑战。报告详细对比了六大框架的性能、易用性和生态。",
    "date": "2026-06-17",
    "views": 6234,
    "comments": 234,
    "url": "http://fiaiweb.com/zh-CN/blog/28-ai-agent-2026/"
  },

  // ===== 大模型 (LLM) - 精选 =====
  {
    "id": "llm-024",
    "title": "Anthropic 发布 Claude Fable5 和 Mythos5：编程与科研突破",
    "category": "大模型",
    "tag": "发布",
    "tagColor": "blue",
    "icon": "🤖",
    "summary": "Anthropic 于 2026-06-10 正式发布 Claude Fable5（通用模型）和 Claude Mythos5（科研专用），Fable5 在 SWE-bench 编程测试中以 72.3% 得分超越 GPT-5，Mythos5 专为科学研究优化。",
    "date": "2026-06-15",
    "views": 5842,
    "comments": 128,
    "url": "https://www.anthropic.com"
  },
  {
    "id": "llm-025",
    "title": "MiniMax 发布 M3 大模型：编程能力超越 GPT-5.5 和 Gemini",
    "category": "大模型",
    "tag": "国产",
    "tagColor": "blue",
    "icon": "🇨🇳",
    "summary": "2026-06-01，MiniMax 正式发布 M3 模型，采用自研稀疏注意力架构 MSA，在 SWE-Bench Pro 编程测试中以 59.0% 得分超越 GPT-5.5 和 Gemini，原生多模态能力同步突破。",
    "date": "2026-06-15",
    "views": 4532,
    "comments": 89,
    "url": "https://www.minimaxi.com"
  },
  {
    "id": "llm-026",
    "title": "GPT-5.6 本月登场：奥特曼确认 AI 自我改进突破",
    "category": "大模型",
    "tag": "重磅",
    "tagColor": "blue",
    "icon": "⚡",
    "summary": "OpenAI CEO 奥特曼确认 GPT-5.6 将于 2026 年 6 月发布，新版本在推理能力和自我改进上取得突破，ChatGPT 同步改版，模型选择简化为六个智能等级选项。",
    "date": "2026-06-15",
    "views": 7234,
    "comments": 312,
    "url": "https://openai.com"
  },
  {
    "id": "llm-027",
    "title": "微软 2026 年 6 月 AI 混战：MAI 模型七连发",
    "category": "大模型",
    "tag": "发布",
    "tagColor": "blue",
    "icon": "🏢",
    "summary": "2026 年 6 月，微软在一周内连续发布 7 个 MAI 系列模型，涵盖基础模型、代码模型、多模态模型等方向，标志着微软在降低对 OpenAI 依赖上取得实质性进展。",
    "date": "2026-06-14",
    "views": 3891,
    "comments": 156,
    "url": "https://www.microsoft.com"
  },
  {
    "id": "llm-001",
    "title": "GPT-5 架构细节泄露：MoE + 稀疏注意力，推理成本降低 60%",
    "category": "大模型",
    "tag": "重磅",
    "tagColor": "blue",
    "icon": "🤖",
    "summary": "OpenAI 下一代旗舰模型 GPT-5 内部测试曝光，采用混合专家架构与稀疏注意力机制，推理成本压缩至 GPT-4 Turbo 的 40%，代码生成与多步推理任务提升显著。",
    "date": "2026-06-13",
    "views": 3842,
    "comments": 128,
    "url": "https://openai.com"
  },
  {
    "id": "llm-002",
    "title": "Claude 4 正式发布：支持 2M Token 上下文，推理能力超越 GPT-5",
    "category": "大模型",
    "tag": "发布",
    "tagColor": "blue",
    "icon": "🤖",
    "summary": "Anthropic 发布 Claude 4 Opus，支持 2M Token 超长上下文，在 SWE-bench 代码测试中以 72.3% 得分超越 GPT-5（68.7%），成为新一代代码王者。",
    "date": "2026-06-12",
    "views": 4521,
    "comments": 89,
    "url": "https://anthropic.com"
  },
  {
    "id": "llm-003",
    "title": "Google Gemini 2.5 Pro 发布：原生多模态 + 实时音视频流",
    "category": "大模型",
    "tag": "多模态",
    "tagColor": "blue",
    "icon": "🌐",
    "summary": "Gemini 2.5 Pro 支持原生实时音视频流输入，延迟低至 280ms，在 MMMU 多模态理解基准上达到 91.2%，超越 GPT-5 与 Claude 4。",
    "date": "2026-06-11",
    "views": 3218,
    "comments": 67,
    "url": "https://deepmind.google"
  },
  {
    "id": "llm-004",
    "title": "Llama 4 开源发布：405B 参数，性能对标 GPT-5",
    "category": "大模型",
    "tag": "开源",
    "tagColor": "green",
    "icon": "🦙",
    "summary": "Meta 发布 Llama 4 系列，旗舰版 405B 参数，在 MMLU Pro 上达到 89.7%，采用全新 MoE 架构，开源协议允许商用，引发社区热烈反响。",
    "date": "2026-06-10",
    "views": 5642,
    "comments": 203,
    "url": "https://llama.meta.com"
  },
  {
    "id": "llm-005",
    "title": "Qwen 3.5 发布：阿里通义千问刷新开源模型纪录",
    "category": "大模型",
    "tag": "国产",
    "tagColor": "blue",
    "icon": "🇨🇳",
    "summary": "阿里通义千问 Qwen 3.5 72B 在中文理解、代码生成、数学推理三项基准上全面超越 Llama 4，成为最强开源中文大模型，支持 128K 上下文。",
    "date": "2026-06-09",
    "views": 4891,
    "comments": 156,
    "url": "https://qwen.ai"
  },

  // ===== Agent - 精选 =====
  {
    "id": "agent-023",
    "title": "2026 年 AI Agent 框架六强争霸：LangGraph、Claude Agent SDK 领先",
    "category": "Agent",
    "tag": "横评",
    "tagColor": "purple",
    "icon": "🏆",
    "summary": "2026 年 6 月，AI Agent 框架从「百花齐放」演变为「六强争霸」：LangGraph、Claude Agent SDK、CrewAI、AutoGPT、OpenClaw、MetaGPT 各有侧重，开发者面临选型挑战。",
    "date": "2026-06-15",
    "views": 6234,
    "comments": 234,
    "url": "http://fiaiweb.com/zh-CN/blog/28-ai-agent-2026/"
  },
  {
    "id": "agent-001",
    "title": "AutoGPT 2.0 发布：支持多 Agent 协同与长期记忆管理",
    "category": "Agent",
    "tag": "开源",
    "tagColor": "purple",
    "icon": "🧩",
    "summary": "开源 Agent 框架 AutoGPT 发布 2.0 版本，引入多 Agent 协同调度引擎与向量数据库长期记忆，任务完成率提升 47%，支持 Docker 容器沙箱执行。",
    "date": "2026-06-13",
    "views": 2156,
    "comments": 67,
    "url": "https://github.com/Significant-Gravitas/AutoGPT"
  },
  {
    "id": "agent-002",
    "title": "CrewAI 1.0 正式发布：多 Agent 协作框架进入生产级",
    "category": "Agent",
    "tag": "生产",
    "tagColor": "purple",
    "icon": "👥",
    "summary": "CrewAI 发布 1.0 正式版，支持 Agent 角色定义、任务委派、工具共享，在 GAIA 基准上以 78.5% 得分位居开源 Agent 框架第一，已被 500+ 企业用于生产环境。",
    "date": "2026-06-12",
    "views": 1876,
    "comments": 54,
    "url": "https://crewai.com"
  },
  {
    "id": "agent-003",
    "title": "LangGraph 新版本发布：支持 Agent 人机协同与中断恢复",
    "category": "Agent",
    "tag": "更新",
    "tagColor": "purple",
    "icon": "🔗",
    "summary": "LangChain 发布 LangGraph 0.3，新增人机协同（Human-in-the-loop）与中断恢复功能，支持长时间运行的 Agent 在中断后从中断点恢复，特别适合复杂业务流程自动化。",
    "date": "2026-06-11",
    "views": 2345,
    "comments": 78,
    "url": "https://langchain.ai"
  },

  // ===== Skill - 精选 =====
  {
    "id": "skill-001",
    "title": "Anthropic 发布 Skill SDK：让 AI Agent 具备可复用技能模块",
    "category": "Skill",
    "tag": "官方",
    "tagColor": "green",
    "icon": "⚡",
    "summary": "Anthropic 正式开源 Skill SDK，允许开发者将专业领域知识封装为可复用 Skill 模块，并支持跨 Agent 框架迁移，首批社区贡献 Skill 已突破 2000 个。",
    "date": "2026-06-12",
    "views": 3021,
    "comments": 112,
    "url": "https://anthropic.com"
  },
  {
    "id": "skill-002",
    "title": "2026 全网最全 AI Skill 开源合集：81 个生产级技能",
    "category": "Skill",
    "tag": "合集",
    "tagColor": "green",
    "icon": "📦",
    "summary": "社区维护的 AI Skill 开源合集更新至 81 个生产级技能，覆盖开发编程、产品设计、DevOps、数据分析、学术科研等全场景，所有链接均经过可用性校验。",
    "date": "2026-06-11",
    "views": 8934,
    "comments": 456,
    "url": "https://github.com"
  },

  // ===== 学术论文 - 精选 =====
  {
    "id": "paper-026",
    "title": "StreamMemBench：流式评估 Agent 记忆机制的未来导向基准",
    "category": "学术论文",
    "journal": "arXiv · 2606.14571 · 2026-06-15",
    "authors": "Guanming Liu, Yuqi Ren et al. · Fudan University",
    "summary": "提出 StreamMemBench 基准，用于流式评估 Agent 记忆机制在未来导向辅助任务上的表现，支持增量式记忆更新与长期任务评估，为 Agent 记忆研究提供标准化测试平台。",
    "date": "2026-06-15",
    "views": 456,
    "comments": 12,
    "url": "https://arxiv.org/abs/2606.14571"
  },
  {
    "id": "paper-027",
    "title": "GitOfThoughts：版本控制推理与可重放 Agent 记忆",
    "category": "学术论文",
    "journal": "arXiv · 2606.14470 · 2026-06-15",
    "authors": "Pavan C Shekar, Abhishek H S et al.",
    "summary": "将版本控制思想引入 Agent 推理与记忆管理，支持推理路径的重放、差异比较与合并，为 Agent 长期学习与多 Agent 协作提供基础设施级支持。",
    "date": "2026-06-15",
    "views": 387,
    "comments": 9,
    "url": "https://arxiv.org/abs/2606.14470"
  },
  {
    "id": "paper-028",
    "title": "CSPO：安全强化学习的约束敏感策略优化（ICML 2026 Spotlight）",
    "category": "学术论文",
    "journal": "ICML 2026 · arXiv:2606.14314",
    "authors": "Ayoub Belouadah, Sylvain Kubler, Yves Le Traon",
    "summary": "提出 CSPO 算法，在安全强化学习中引入约束敏感度感知机制，在保持安全约束满足率的同时显著提升策略性能，入选 ICML 2026 Spotlight 论文。",
    "date": "2026-06-15",
    "views": 678,
    "comments": 23,
    "url": "https://arxiv.org/abs/2606.14314"
  },

  // ===== 技术突破 - 精选 =====
  {
    "id": "break-001",
    "title": "DeepMind 新论文：推理时计算扩展定律正式验证",
    "category": "技术突破",
    "tag": "推理",
    "tagColor": "cyan",
    "icon": "🚀",
    "summary": "DeepMind 团队在 arXiv 发布最新研究成果，系统验证了推理时计算资源扩展与模型性能的对数线性关系，为 test-time compute 路线提供理论支撑，引发社区广泛讨论。",
    "date": "2026-06-13",
    "views": 1873,
    "comments": 67,
    "url": "https://deepmind.google"
  },
  {
    "id": "break-002",
    "title": "2026 上半年 AI 大模型格局报告：开源模型首次在推理任务上超越商业闭源模型",
    "category": "技术突破",
    "tag": "报告",
    "tagColor": "orange",
    "icon": "📊",
    "summary": "斯坦福 HAI 研究所发布《2026 AI Index Report》，核心发现：开源大模型（Llama 4、Qwen 3、DeepSeek V4）在 MMLU、HumanEval 等基准上首次集体超越 GPT-4o 与 Claude 3.5 Sonnet。",
    "date": "2026-06-11",
    "views": 5067,
    "comments": 312,
    "url": "https://hai.stanford.edu"
  }
];
